config/routes.rb
Rails.application.routes.draw do
  root 'games#index'

  resources :games, :only => [:index, :show, :destroy] do
    resource :fen, :only => [:show]
    resource :note, :only => [:update]
  end

  resource :pgn, :only => [:new, :create]
end

app/models/fen_list.rb
class FenList
  attr_accessor :game, :list

  def self.for_game(game)
    new(:game => game).generate!
  end

  def initialize(attrs, pgn_parser = PGN)
    self.pgn_parser = pgn_parser
    self.game       = attrs.fetch(:game)
    self.list       = {}
  end

  # generates fens for each move in the PGN
  def generate!
    pgn = pgn_parser.parse(game.pgn).first

    positions = pgn.positions[1..-1]

    positions.each_with_index.inject(1) do |move_number, (position, index)|

      if index % 2 == 1
        list["#{move_number}"].push(position.to_fen.to_s)
        move_number +=1
      elsif index % 2 == 0 #even
        list["#{move_number}"] = [position.to_fen.to_s]
      end

      move_number
    end

    list
  end


  private

  attr_accessor :pgn_parser
end

app/models/game.rb
class Game < ActiveRecord::Base

  validates :white, :black, :result, :presence => true

  def moves
    match_moves = pgn.match(/]\s+(1\..*)\s\d-\d/)[1]
    match_moves.gsub!(/\s{.*?}/,"") #remove comments
    match_moves.gsub!(/\s\(.*?\)/,"") #remove variations
    match_moves
  end
end

app/models/pgn.rb
class Pgn
  include ActiveModel::Model

  attr_accessor :text

  validates :text, :presence => true
  validate :check_format!

  def initialize(attrs = {}, parser = PGN)
    self.parser = parser
    super(attrs)
  end

  def save
    return false unless valid?
    Game.create!(game_params)
    true
  end


  private

  attr_accessor :parser, :game_params, :pgn_game

  def check_format!
    return if text.blank?

    begin
      clean!
      self.pgn_game = parser.parse(text).first
    rescue
      could_not_be_parsed!
      return
    end

    build_game_params!
    check_game_params!
  end

  def clean!
    text.strip! #remove white space from ends of string
    text.gsub!(/[\u201c|\u201d]/, "\"") #replace unicode quotation marks
    text.gsub!(/\$\d+\s/, "") #removes NAG
    text.gsub!(/;/, "") #remove semi-colon
  end

  def build_game_params!
    self.game_params = { :white  => pgn_game.tags["White"],
                         :black  => pgn_game.tags["Black"],
                         :result => pgn_game.tags["Result"],
    }
  end

  def check_game_params!
    game = new_game(game_params)
    if !game.valid?
      add_errors_from_game(game)
    else
      text.gsub!(/\r/, "") #removes carriage return
      text.gsub!(/\n/, " ") #replace new line with space
      self.game_params = game_params.merge(:pgn => text)
    end
  end

  def new_game(game_params)
    Game.new(game_params)
  end

  def add_errors_from_game(game)
    game.errors.messages.each do |err_key, err_msg|
      errors.add(err_key, err_msg.first)
    end
  end

  def could_not_be_parsed!
    errors.add(:pgn, "could not be parsed, please check your formatting.")
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/fens_controller.rb
class FensController < ApplicationController

  def show
    game = Game.find(params[:game_id])

    build_fen = PGN.parse("[Dummy \"Tag\"]" + game[:pgn]).first
    build_fen.positions.delete_at(0)

    @fens = []
    build_fen.positions.each_with_index.inject(1) do |counter, (pos, index)|
      # Parser Generates an incorrect "Fullmove number" thats starts at 0
      # should start at one
      fen = pos.to_fen.to_s[0...-1] + counter.to_s
      @fens << fen
      counter += 1
    end


    respond_to do |format|
      format.json { render json: @fens }
    end

  end

end

app/controllers/games_controller.rb
class GamesController < ApplicationController

  def index
    @games = Game.all
  end

  def show
    @game = Game.find(params[:id])
  end

  def destroy
    game = Game.find(params[:id])
    game.destroy
    redirect_to root_path, :notice => "Game Deleted!"
  end
end

app/controllers/pgns_controller.rb
class PgnsController < ApplicationController

  def new
    @pgn = Pgn.new
  end

  def create
    @pgn = Pgn.new(pgn_params)

    if @pgn.save
      redirect_to root_path, :notice => "Game Saved!"
    else
      render :new
    end
  end


  private

  def pgn_params
    params.require(:pgn).permit(:text)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/games/index.erb
<div class="container-fluid">
  <div class="panel panel-default">
    <!-- Default panel contents -->
    <div class="panel-heading"><h3><%= "Game List" %></h3>

      <div class="filter">
        <input type="text" id="search-input" class="form-control" placeholder="Filter"/>
      </div>
    </div>
    <table class="table table-hover">
      <thead>
      <tr>
        <th></th>
        <th>#</th>
        <th></th>
        <th>White</th>
        <th>Black</th>
        <th>Result</th>
        <th></th>
      </tr>
      </thead>

      <tbody>
      <% if @games.length > 0 %>
        <% @games.each_with_index do |game, index| %>
          <tr>
            <td></td>
            <td><%= index + 1 %></td>
            <td><%= link_to game_path(game) do %>
                <span class="glyphicon glyphicon-play-circle"></span>
              <% end %>
            </td>
            <td><%= game[:white] %></td>
            <td><%= game[:black] %></td>
            <td><%= game[:result] %></td>
            <td>
              <%= button_to game_path(game), method: :delete, class: "btn remove-game" do %>
                <span class="glyphicon glyphicon-remove"></span>
              <% end %>
            </td>
          </tr>
        <% end %>
      <% else %>
        <h3 class="text-center">No games, try creating one!</h3>
      <% end %>
      </tbody>
    </table>
  </div>
</div>

<div class="col-lg-2"></div>
</div>

app/views/games/new.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-lg-4"></div>

    <div class="col-lg-4">
      <% if @game.errors.any? %>
        <div class="alert alert-danger" role="alert">
          <% @game.errors.full_messages.each do |err| %>
            <p><%= err %></p>
          <% end %>
        </div>
      <% end %>
    </div>

    <div class="col-lg-4"></div>
  </div>

  <div class="row">
    <div class="col-lg-4"></div>

    <div class="col-lg-4">
      <%= form_tag(games_path, :method => :post, :class => "form hid") do %>
        <div class="form-group">
          <%= label_tag(:text, "Copy/Paste PGN") %> <%= link_to "Example", "#", :id => "example" %>
          <%= text_area_tag(:text, "", :size => "24x20", :class => "form-control") %>
        </div>
        <%= submit_tag("Submit", :class => "btn") %>
      <% end %>
    </div>

    <div class="col-lg-4"></div>
  </div>

</div>

<script>
  $(document).ready(function() {

    setTimeout(function(e) {

      $('.hid').show('clip', 500);

    }, 100);

    $('#example').on('click', function(e) {
      e.preventDefault();

      var exPGN = '[Event "Riga ;MAINB"]\n[Site "Riga ;MAINB"]\n[Date "1957.??.??"]\n[EventDate "?"]\n[Round "?"]\n[Result "1-0"]\n[White "Mikhail Tal"]\n[Black "Alexander Koblents"]\n1.e4 c5 2.Nf3 d6 3.d4 cxd4 4.Nxd4 Nf6 5.Nc3 Nc6 6.Bg5 {this is an inline comment followed by a variation} e6 (6... e5 7.Qd3 exd4) 7.Qd2 Be7 8.O-O-O O-O 9.Nb3 Qb6 10.f3 a6 11.g4 Rd8 12.Be3 Qc7 13.h4 b5 14.g5 Nd7 15.g6 hxg6 16.h5 gxh5 17.Rxh5 Nf6 18.Rh1 d5 19.e5 Nxe5 20.Bf4 Bd6 21.Qh2 Kf8 22.Qh8+ Ng8 23.Rh7 f5 24.Bh6 Rd7 25.Bxb5 Rf7 26.Rg1 Ra7 27.Nd4 Ng4 28.fxg4 Be5 29.Nc6 Bxc3 30.Be3 d4 31.Rgh1 Rd7 32.Bg5 axb5 33.R1h6 d3 34.bxc3 d2 35.Kd1 Qxc6 36.Rf6+ Rf7 37.Qxg7+ 1-0';

      var textArea = $('textarea');
      textArea.val(exPGN);
    });
  });
</script>

app/views/games/show.erb
<div class="container-fluid" xmlns:id="http://www.w3.org/1999/xhtml">
  <div class="row">

    <div class="col-lg-12">

      <div id="board" style="padding-left:20%;width: 500px"></div>

      <button class="btn btn-primary" id="startBtn">Start</button>

      <button class="btn btn-primary" id="backBtn">
        <span class="glyphicon glyphicon-chevron-left"></span>
      </button>

      <button class="btn btn-primary" id="fwdBtn">
        <span class="glyphicon glyphicon-chevron-right"></span>
      </button>

      <p>Fen:</p>
      <p><span id="fen"></span></p>

    </div>
  </div>

</div>
<script type="text/javascript" charset="utf-8">
  var pgn = "<%= @game.moves %>";

  var pgnViewer = PgnViewer(pgn, "<%= game_fen_path(@game) %>");
</script>

app/views/global/_errors.erb
<div class="row">
  <div class="col-lg-4"></div>

  <div class="col-lg-4">
    <% if errors.any? %>
      <div class="alert alert-danger text-center" role="alert">
        <% errors.full_messages.each do |err| %>
          <p><%= err %></p>
        <% end %>
      </div>
    <% end %>
  </div>

  <div class="col-lg-4"></div>
</div>

app/views/global/_flash.erb
<div class="row container-fluid">
  <div class="col-lg-12">
    <% if flash.any? %>
      <div class="alert alert-success text-center" role="alert">
        <p><%= flash[:notice] %></p>
      </div>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Chessly</title>
  <%= javascript_include_tag 'application' %>
  <!-- Latest compiled and minified CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">

  <!-- Optional theme -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap-theme.min.css">

  <!-- Latest compiled and minified JavaScript -->
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>

  <%= stylesheet_link_tag 'application', media: 'all' %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="row">
  <div class="col-lg-12">
    <nav class="navbar navbar-default" role="navigation">
      <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <%= link_to "Chessly", root_path, class: "navbar-brand" %>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav">
            <li><%= link_to "Create Game", new_pgn_path %></li>
            <li><%= link_to "List Games", root_path %></li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <li></li>
          </ul>
        </div>
      </div>
    </nav>
  </div>
</div>
<div class="ui-hidden">
  <%= render "global/flash" %>
  <%= yield %>
</div>
</body>
</html>

app/views/pgns/new.erb
<div class="container-fluid">
  <%= render "global/errors", :errors => @pgn.errors %>

  <div class="row">
    <div class="col-lg-4"></div>

    <div class="col-lg-4">
      <%= form_for @pgn, :url => pgn_path, :class => "form hid" do |f| %>
        <div class="form-group">
          <%= f.label(:text, "Copy/Paste PGN") %> <%= link_to "Example", "#", :id => "example" %>
          <%= f.text_area(:text, :size => "24x20", :class => "form-control") %>
        </div>
        <%= submit_tag("Submit", :class => "btn") %>
      <% end %>
    </div>

    <div class="col-lg-4"></div>
  </div>

</div>